stages:
  - test
  - build
  - deploy


# Étape pour le build et le push de l'image Docker
docker_build_and_push:
  stage: build
  script:
    - docker build -t image:latest .
    - docker login -u ${{secrets.Docker_sec}} -p ${{secrets.Docker_pass}} 
    - docker push image:latest
  only:
    - feature/hajer/add-docker-buikd-push-step-to-ci
